### ISSUE TITLE
I found a bug with your game

### ISSUE THREAD

**Issue by Zavier-Hastings** [caleblaroche14/MDCC-CIS4520#1]
So I was playing your game and when I defeated a mob it didn't die, it just kept beating me up and there was nothing I could do. Fix your game plz

**Comment by caleblaroche14** [comment]
Good to know! Although we thought about just torturing our players, we should probably give you a way to not die..... maybe....

**Comment by cdf01260** [comment]
Definitely Fixed. Nothing to see here

**Comment by anaptyxis** [comment]
Maybe he's just a sweat

**Comment by anaptyxis** [comment]
You should close this issue.
